### ISSUE TITLE
BlockMerging出错！！！

### ISSUE THREAD

**Issue by swjtu-jia-wei** [WXinlong/ASIS#44]
我使用了您的训练模型，并且下载了完整且没有错误的S3DIS数据用于测试。
但是在BlockMerging这里出现了 :     index 129 is out of bounds for axis 0 with size 100这样的问题。
想请教您这个问题到底出在哪里了呢？

**Comment by LH1005** [comment]
Hi, I'm running this model, too. The inference_merge.py file was found missing during training. Have you ever encountered this problem? Do you have this file to share?

**Comment by jianuo1128** [comment]
@swjtu-jia-wei @LH1005 @WXinlong hello! have encountered the same issue, like this: 
Traceback (most recent call last):
  File "test.py", line 261, in <module>
    test()
  File "test.py", line 202, in test
    groupids_block.astype(np.int32), group_seg, gap)
  File "/mnt/pjn/segment/ASIS/utils/test_utils.py", line 184, in BlockMerging
    groupcounts[grouplabel[i]] += 1
IndexError: index 686 is out of bounds for axis 0 with size 100

that's why? i can't understand
